### ISSUE TITLE
can you add something like --serveraddress?

### ISSUE THREAD

**Issue by waternoob1005** [OpenFarLands/TheStoneProxy#10]
TheStoneProxy.exe --serveraddress 127.0.0.1:19132

**Comment by mikhaillav** [comment]
Thank you for your issue!

But i think it's a bit confusing because proxy has an **address for listening for income connections**  and **address for transferring packets to the origin server** as well, so you can't really say which one is `--serveraddress `.  You can specify `Local` and `Remote` addresses in the [config file.](https://github.com/OpenFarLands/TheStoneProxy/blob/main/example.config.toml)
![image](https://github.com/OpenFarLands/TheStoneProxy/assets/59438110/b73bb43a-9f8c-41cd-914d-4d3cc7d7dbae)

**Comment by waternoob1005** [comment]
Okay. I understand. So what about being able to change the proxy address by typing it into the terminal?

**Comment by mikhaillav** [comment]
I don't think it's necessary since you have a config file
